### ISSUE TITLE
Remove FFmpeg use in WaveBank/SoundEffect processors

### ISSUE THREAD

**Issue by flibitijibibo** [0x0ade/XnaToFna#12]
Now that FNA's on FAudio, it's much more realistic for us to include WMA support as a native feature:

https://github.com/FNA-XNA/FAudio/issues/32

This should be removed and effort should go towards WMA support in FAudio.

**Comment by flibitijibibo** [comment]
The FFmpeg patch is now in, so removal of this stuff can start whenever someone has time.

**Comment by 0x0ade** [comment]
Gonna work on it later this week now that the FAudio patch is finally merged in 🎉

Sidenote: I know that someone in the Terraria modding community uses the audio content transformers. Luckily they've already copied the necessary code from XnaToFna to their own project, but I'd like to keep it somewhere if it finds some use for someone in the future ever again (it really shouldn't - it's horrible).
