### ISSUE TITLE
Is this used to play Xbox Live arcade indie games on the pc?

### ISSUE THREAD

**Issue by irrelevantpelican** [0x0ade/XnaToFna#18]
Hello, sorry I'm not sure if I'm in the right place. I've been searching high and low to find a way to play some Xbox live indie arcade games i legally purchased and backed up to my Pc. Is this possible?

**Comment by Margen67** [comment]
#3

**Comment by flibitijibibo** [comment]
Closing out some of the old questions that have been answered...
