### ISSUE TITLE
Is it can support for XNA3.1's game...?

### ISSUE THREAD

**Issue by PaienNate** [0x0ade/XnaToFna#22]
I wanna to try to play Magicka on linux but it doesn't have XNA3.1.I have a search and find that Duck Game use XNAtoFNA to do that.and I download the file and have a try.but I forgot it is a XNA 3.1 game and when I tried it ,it tolds me that the version is not match (old?I am chinese so the error is in chinese,and I don't know what it in ENGLISH)
I have a look and found it's a error for MonoMod,and I download a new version from the MonoMod github,but the software XNAtoFNA crashed.

**Comment by flibitijibibo** [comment]
XnaToFna and FNA are unable to support 3.1 or older.
