### ISSUE TITLE
Content directory

### ISSUE THREAD

**Issue by thfrwn** [0x0ade/XnaToFna#5]
I've been looking some at Underrail (GOG version). The content is in a `data` directory, but XnaToFna.exe tells me that it expects a `Content` directory and if I rename `data` to `Content`, it processes the files in there.

Now my question: how does this work at runtime? does runtime expect the content files now in `data` or in `Content`?

**Comment by 0x0ade** [comment]
I never got Underrail to work myself. Nevertheless, the game still expects data in `data`. 

Just pass `--content data` as an argument to XnaToFna, which adds `data` to the scanned content directories.

**Comment by thfrwn** [comment]
Thanks. How far did you get? Here a window opens, but is black and nothing happens. To me this seems like it initializes, but likely doesn't find the content. Also no log where I could see what's going on.

**Comment by 0x0ade** [comment]
I got into the main menu, but not much further. Someone here got in-game, but with a black screen: https://github.com/0x0ade/XnaToFna-Tracker/issues/3#issuecomment-340448093

**Comment by thfrwn** [comment]
thanks, will see how much I can replicate here... it's unlikely to get any further than he got, but hey it's fun

**Comment by thfrwn** [comment]
Looks like I'll need to compile csfml libraries and maybe sfmlnet to get farther.

I only now understood that you use the issues tab of XnaToFna-Tracker for the tracking. After a little more testing I think it would be good to add Axiom Verge there. For platforms without steam, or those who get the DRM-free Collector's edition and want to play on non-Windows system, XnaToFna is going to be the way IMO.
